#!/usr/bin/env python3
"""Generate the compressed-format fixtures embedded in src/samplecheck_fixtures.h.

The --samplecheck §4 section (PLAN.md §6 phase 4) needs tiny MP3 / FLAC /
Ogg Vorbis fixtures plus an Ogg Opus file for the wrong-codec refusal. The
harness is self-contained (no fixture paths at runtime), so the encoded bytes
are embedded as C arrays. Re-running this script regenerates the header;
lossy encoder output can differ across libsndfile/lame/libvorbis versions,
so the golden decode values hard-coded in samplecheck.cpp must be re-derived
(the harness prints actual values on mismatch) whenever the fixtures change.

Requires: numpy, soundfile (libsndfile >= 1.1 with lame/vorbis/opus).
Usage: python3 make_fixtures.py   (writes src/samplecheck_fixtures.h
       relative to the repo root, found from this script's location)
"""

import io
import pathlib

import numpy as np
import soundfile as sf

REPO = pathlib.Path(__file__).resolve().parents[3]
OUT = REPO / "src" / "samplecheck_fixtures.h"


def sine(freq, rate, seconds, amp):
    n = int(rate * seconds)
    return amp * np.sin(2.0 * np.pi * freq * np.arange(n) / rate)


def encode(data, rate, fmt, subtype):
    buf = io.BytesIO()
    sf.write(buf, data, rate, format=fmt, subtype=subtype)
    return buf.getvalue()


def c_array(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main():
    # 440 Hz sine, amp 0.5 — mono 22050 Hz except where noted.
    mono = sine(440.0, 22050, 0.25, 0.5)
    mp3 = encode(mono, 22050, "MP3", "MPEG_LAYER_III")
    flac = encode(mono, 22050, "FLAC", "PCM_24")
    # Stereo, in-phase (R = 0.8·L): exercises the compressed-path downmix.
    stereo = np.column_stack([mono, 0.8 * mono])
    ogg = encode(stereo, 22050, "OGG", "VORBIS")
    # Opus only accepts 8/12/16/24/48 kHz input; any Ogg-not-Vorbis will do.
    opus = encode(sine(440.0, 16000, 0.25, 0.5), 16000, "OGG", "OPUS")

    fixtures = [
        ("kFixtureMp3", mp3, "MP3 (lame): 440 Hz sine, amp 0.5, mono 22050 Hz, 0.25 s"),
        ("kFixtureFlac", flac, "FLAC 24-bit: same mono sine"),
        ("kFixtureOgg", ogg, "Ogg Vorbis: stereo, L = sine amp 0.5, R = 0.8*L"),
        ("kFixtureOpus", opus, "Ogg Opus (wrong-codec refusal): mono 16000 Hz sine"),
    ]

    parts = [
        "// Generated by docs/sample-studio/tools/make_fixtures.py — do not edit.",
        "// Compressed-format fixtures for --samplecheck section 4. Regenerating",
        "// with a different libsndfile/lame/libvorbis can change the encoded",
        "// bytes; re-derive the golden decode values in samplecheck.cpp then.",
        f"// libsndfile: {sf.__libsndfile_version__}",
        "#pragma once",
        "",
    ]
    for name, data, desc in fixtures:
        parts.append(f"// {desc} ({len(data)} bytes)")
        parts.append(c_array(name, data))
        parts.append(f"static const unsigned int {name}Len = {len(data)};")
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")
    for name, data, _ in fixtures:
        print(f"  {name}: {len(data)} bytes")


if __name__ == "__main__":
    main()
